"""GitOps remediation channel — turns a Finding into a reviewable Pull Request.

This is the Trust-Gap mechanism in code:
  - the agent has ZERO cloud write access; its only "action" is opening a PR,
  - managed resources -> a diff against the IaC,
  - UNMANAGED (ClickOps) -> a FLAT `cloudcap_clickops_recovery.tf` + import (no
    reverse-engineering of the customer's module/Terragrunt layout),
  - a semantic policy gate runs BEFORE a human sees the PR,
  - the PR body leads with DETERMINISTIC PROOF, not AI prose.

Runs today via MockGitBackend (writes PR artifacts to disk). Swap GitHubBackend
for `--mode live`; the channel logic is identical.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any

from agents.ports.interfaces import ManagementSource, RemediationChannelPort
from agents.remediation.quarantine import quarantine_for

TF_FILE = "terraform/chaos-env/main.tf"  # demo target; real repo path is configured at install


@dataclass
class RemediationPlan:
    resource: str
    branch: str
    title: str
    change_kind: str                       # rightsize | iam-tighten | delete | codify
    diff: str | None = None                # unified-diff hunk for managed edits
    files: dict[str, str] = field(default_factory=dict)  # extra files (recovery .tf)
    commands: list[str] = field(default_factory=list)    # e.g. terraform import
    quarantine: dict[str, str] | None = None
    repo: str | None = None                # resolved owning repo (from IaC state index)


# --- change generation ------------------------------------------------------
def _slug(res: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in res).strip("-").lower()[:48]


def _change(path: str, old: str, new: str) -> str:
    return f"--- a/{path}\n+++ b/{path}\n@@\n-{old}\n+{new}\n"


def _delete_block(path: str, addr: str, body: str) -> str:
    lines = "\n".join(f"-{ln}" for ln in body.strip().splitlines())
    return f"--- a/{path}\n+++ b/{path}\n@@ remove {addr} @@\n{lines}\n"


def _recovery_hcl(res: str) -> str:
    return (
        "# Generated by CloudCap — FLAT recovery file at repo ROOT.\n"
        "# Do NOT hand-edit into modules yet; refactor after merge. Bound to live\n"
        "# infra via the `terraform import` in IMPORT.sh so no resource is recreated.\n"
        'resource "google_compute_instance" "recovered" {\n'
        f'  name = "{res}"\n'
        "  # Attributes populate on `terraform plan` after import.\n"
        "  lifecycle { prevent_destroy = true }\n"
        "}\n"
    )


def propose(f: dict[str, Any]) -> RemediationPlan | None:
    """Map a finding to a concrete, minimal, reviewable change (or None if alert-only)."""
    res = f["resource"]
    md = f.get("metadata", {})
    branch = f"cloudcap/fix-{_slug(res)}"
    owner_repo = md.get("owner_repo")

    # Alert-only findings (e.g. a blocked injection) get no code PR — check FIRST,
    # before ownership routing (a poisoned object is not a resource to codify).
    if f.get("id", "").startswith("sec/tool-poisoning"):
        return None

    # Hardcoded secret in the repo's IaC — the scanner precomputed the exact fix
    # (literal → sensitive variable). Commit those files verbatim as a real PR.
    if md.get("fix_kind") == "redact-secret" and md.get("fix_files"):
        return RemediationPlan(
            resource=res, branch=md.get("fix_branch") or branch,
            title=f"Remove hardcoded secret from {md.get('file', res)} (use a sensitive variable)",
            change_kind="redact-secret",
            files=dict(md["fix_files"]),
            repo=owner_repo,
        )

    # CONFLICT — multiple Terraform states claim this resource. Never auto-PR; the
    # ambiguity must be triaged by a human (which state should own it?).
    if md.get("ownership_status") == "conflict":
        return RemediationPlan(
            resource=res, branch=branch, change_kind="conflict",
            title=f"[TRIAGE] {res} is managed by multiple Terraform states")

    # UNMANAGED (ClickOps / not in any state) -> codify-then-PR + quarantine plan.
    if md.get("ownership_status") == "unmanaged" or \
            md.get("management_source") == ManagementSource.UNMANAGED.value:
        return RemediationPlan(
            resource=res, branch=branch,
            title=f"Codify + quarantine out-of-band resource {res}",
            change_kind="codify",
            files={"cloudcap_clickops_recovery.tf": _recovery_hcl(res)},
            commands=[f"terraform import google_compute_instance.recovered {res}"],
            quarantine=quarantine_for("compute.instance"),
        )

    r = res.lower()
    if "public-bucket" in r:
        return RemediationPlan(
            resource=res, branch=branch, title=f"Remove public access from {res}",
            change_kind="iam-tighten",
            diff=_delete_block(TF_FILE, "google_storage_bucket_iam_member.public_read",
                               'role   = "roles/storage.objectViewer"\nmember = "allUsers"'),
            quarantine=quarantine_for("storage.bucket"),
        )
    if "over-privileged" in r:
        return RemediationPlan(
            resource=res, branch=branch,
            title=f"Replace roles/owner with least-privilege on {res}",
            change_kind="iam-tighten",
            diff=_change(TF_FILE, 'role    = "roles/owner"', 'role    = "roles/viewer"'),
        )
    if "idle-oversized-vm" in r:
        return RemediationPlan(
            resource=res, branch=branch, title=f"Downsize idle VM {res}",
            change_kind="rightsize",
            diff=_change(TF_FILE, 'machine_type = "e2-standard-4"', 'machine_type = "e2-small"'),
            quarantine=quarantine_for("compute.instance"),
        )
    if "oversized-sql" in r:
        return RemediationPlan(
            resource=res, branch=branch, title=f"Rightsize Cloud SQL {res}",
            change_kind="rightsize",
            diff=_change(TF_FILE, "tier            = var.oversized_sql_tier",
                         'tier            = "db-custom-1-3840"'),
        )
    if "orphan-disk" in r:
        return RemediationPlan(
            resource=res, branch=branch, title=f"Remove orphaned disk {res} (snapshot first)",
            change_kind="delete",
            diff=_delete_block(TF_FILE, "google_compute_disk.orphan_disk",
                               'name = "cc-orphan-disk"\ntype = "pd-ssd"\nsize = 200'),
            quarantine=quarantine_for("compute.disk"),
        )
    return None


# --- semantic policy gate (Agent Gateway policy enforcement) ----------------
def policy_gate(plan: RemediationPlan) -> tuple[bool, str]:
    """Evaluate the proposed change against org policy BEFORE a human sees it."""
    if plan.change_kind == "delete" and not plan.quarantine:
        return False, "delete proposed without a reversible quarantine step"
    return True, "ok"


def render_pr_body(f: dict[str, Any], proof: dict[str, Any], plan: RemediationPlan) -> str:
    md = f.get("metadata", {})
    lines = [
        f"### CloudCap remediation: {f['title']}",
        "",
        f"**Resource:** `{f['resource']}`  ",
        f"**Severity:** {f['severity']}  ",
        f"**Est. monthly savings:** ${f.get('est_monthly_savings_usd', 0):,.0f}  ",
        f"**Management source:** {md.get('management_source', 'unknown')}",
    ]
    if md.get("owner_repo"):
        lines.append(f"**IaC owner (resolved from state):** `{md['owner_repo']}` "
                     f"→ `{md.get('tf_address', '')}`")
    if md.get("management_source") == ManagementSource.UNMANAGED.value:
        lines += [
            "",
            "#### Attribution (out-of-band resource)",
            f"- created_by: `{md.get('created_by')}`",
            f"- real actor (assumption chain): {md.get('triggering_entity')}",
            f"- confidence: {md.get('attribution_confidence')}",
        ]
    lines += [
        "",
        "#### Proof (deterministic — not an AI assertion)",
        f"- {proof.get('summary', 'n/a')}",
        f"- {proof.get('note', '')}",
    ]
    if plan.quarantine:
        lines += [
            "",
            "#### Quarantine-first plan (reversible)",
            f"1. {plan.quarantine['reversible']}",
            "2. soak N days; abort on any activity",
            f"3. {plan.quarantine['terminal']}",
        ]
    lines += [
        "",
        "_Review the diff / recovery file below. Merge + `terraform apply` applies the "
        "change. This agent has NO cloud write access._",
    ]
    return "\n".join(lines)


# --- git backends -----------------------------------------------------------
class MockGitBackend:
    """Writes PR artifacts to disk so the flow is inspectable with no GitHub access."""

    def __init__(self, out_dir: str = "eval/prs") -> None:
        self.out_dir = out_dir

    async def open_pr(self, repo, branch, title, body, files, commands) -> dict[str, Any]:
        d = os.path.join(self.out_dir, branch.replace("/", "__"))
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "PR.md"), "w") as fh:
            fh.write(f"# {title}\n\n(repo: {repo}, branch: {branch})\n\n{body}\n")
        for name, content in files.items():
            with open(os.path.join(d, name.replace("/", "__")), "w") as fh:
                fh.write(content)
        if commands:
            with open(os.path.join(d, "IMPORT.sh"), "w") as fh:
                fh.write("#!/usr/bin/env bash\nset -euo pipefail\n" + "\n".join(commands) + "\n")
        return {"status": "pr_opened", "repo": repo, "branch": branch, "path": d,
                "artifacts": len(files) + (1 if commands else 0)}


class GitHubBackend:
    """Live GitHub PR backend — opens a real Pull Request via the GitHub REST API.

    Uses urllib + a token (constructor or GITHUB_TOKEN env, sourced from Secret
    Manager on deploy) so it runs anywhere without the `gh` binary. The agent's ONLY
    write is opening a PR on a branch; nothing is merged and no cloud is touched."""

    _API = "https://api.github.com"

    def __init__(self, repo: str | None = None, token: str | None = None) -> None:
        import os
        self.repo = repo
        self.token = token or os.environ.get("GITHUB_TOKEN", "")

    def _req(self, method: str, path: str, body: dict | None = None) -> tuple[int, dict]:
        import json as _json
        import urllib.error
        import urllib.request
        url = path if path.startswith("http") else f"{self._API}{path}"
        data = _json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, method=method, headers={
            "Accept": "application/vnd.github+json", "User-Agent": "cloudcap",
            "Authorization": f"Bearer {self.token}", "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                return r.status, _json.load(r)
        except urllib.error.HTTPError as e:
            try:
                return e.code, _json.load(e)
            except Exception:
                return e.code, {"message": str(e)}

    def _get_content_sha(self, repo: str, path: str, branch: str) -> str | None:
        st, d = self._req("GET", f"/repos/{repo}/contents/{path}?ref={branch}")
        return d.get("sha") if st == 200 else None

    async def open_pr(self, repo, branch, title, body, files, commands) -> dict[str, Any]:
        import base64
        if not self.token:
            return {"status": "pr_error", "repo": repo, "reason": "no GITHUB_TOKEN configured"}

        # 1. default branch + its head SHA
        st, meta = self._req("GET", f"/repos/{repo}")
        if st != 200:
            return {"status": "pr_error", "repo": repo, "reason": f"repo lookup {st}: {meta.get('message')}"}
        base = meta.get("default_branch", "main")
        st, ref = self._req("GET", f"/repos/{repo}/git/ref/heads/{base}")
        if st != 200:
            return {"status": "pr_error", "repo": repo, "reason": f"base ref {st}: {ref.get('message')}"}
        base_sha = ref["object"]["sha"]

        # 2. create the branch (idempotent — reuse if it already exists)
        st, r = self._req("POST", f"/repos/{repo}/git/refs",
                          {"ref": f"refs/heads/{branch}", "sha": base_sha})
        if st not in (200, 201) and "already exists" not in str(r.get("message", "")).lower():
            return {"status": "pr_error", "repo": repo, "reason": f"branch {st}: {r.get('message')}"}

        # 3. commit each file onto the branch (create or update via Contents API)
        committed = []
        for path, content in (files or {}).items():
            payload = {"message": f"CloudCap: {title}", "branch": branch,
                       "content": base64.b64encode(content.encode()).decode()}
            sha = self._get_content_sha(repo, path, branch)
            if sha:
                payload["sha"] = sha
            st, r = self._req("PUT", f"/repos/{repo}/contents/{path}", payload)
            if st not in (200, 201):
                return {"status": "pr_error", "repo": repo, "reason": f"commit {path} {st}: {r.get('message')}"}
            committed.append(path)

        # 4. open the PR
        st, pr = self._req("POST", f"/repos/{repo}/pulls",
                           {"title": title, "head": branch, "base": base, "body": body})
        if st not in (200, 201):
            # a PR for this head may already be open — surface it rather than erroring
            st2, existing = self._req("GET", f"/repos/{repo}/pulls?head={repo.split('/')[0]}:{branch}&state=open")
            if st2 == 200 and existing:
                pr = existing[0]
            else:
                return {"status": "pr_error", "repo": repo, "reason": f"pr {st}: {pr.get('message')}",
                        "committed": committed}
        return {"status": "pr_opened", "repo": repo, "branch": branch,
                "url": pr.get("html_url"), "number": pr.get("number"), "files": committed}


# --- channel ----------------------------------------------------------------
class PullRequestChannel(RemediationChannelPort):
    def __init__(self, backend, repo: str = "acme/infra") -> None:
        self.backend = backend
        self.repo = repo

    async def can_handle(self, source: ManagementSource) -> bool:
        return True  # PR (managed) or codify-then-PR (unmanaged) covers all sources here

    async def deliver(self, proposal: dict[str, Any]) -> dict[str, Any]:
        f = proposal["finding"]
        proof = proposal.get("proof") or {}
        plan = propose(f)
        if plan is None:
            return {"status": "skipped", "resource": f["resource"], "reason": "alert-only / no code change"}

        # CONFLICT — resolved to multiple owners; route to human triage, no PR.
        if plan.change_kind == "conflict":
            return {"status": "conflict_triage", "resource": f["resource"],
                    "reason": "managed by multiple Terraform states — routed to human triage",
                    "candidates": f.get("metadata", {}).get("owner_candidates", [])}

        ok, reason = policy_gate(plan)
        if not ok:
            return {"status": "policy_blocked", "resource": f["resource"], "reason": reason}

        # Route the PR to the RESOLVED owning repo (managed) or the recovery repo (codify).
        # SAFETY: a real backend opens PRs ONLY against a genuinely resolved owner repo —
        # never the placeholder default. So a finding with no repo bound (e.g. a live GCP
        # posture finding, or any kitearc-prod finding) is report-only, and no repo we did
        # not explicitly bind can ever receive a PR.
        repo = plan.repo or f.get("metadata", {}).get("owner_repo")
        if not repo:
            if isinstance(self.backend, MockGitBackend):
                repo = self.repo  # inspectable disk artifact against the demo placeholder
            else:
                return {"status": "skipped", "resource": f["resource"],
                        "reason": "no owning repo bound — report-only"}
        body = render_pr_body(f, proof, plan)
        files = dict(plan.files)
        if plan.diff:
            files["PROPOSED_CHANGE.diff"] = plan.diff
        result = await self.backend.open_pr(repo, plan.branch, plan.title, body, files, plan.commands)
        result["kind"] = plan.change_kind
        result["resource"] = f["resource"]
        result["fingerprint"] = f.get("fingerprint")
        return result


def _open_ticket(f: dict[str, Any], reason: str = "") -> dict[str, Any]:
    """Route the Issue action to JIRA when configured; else a local ticket artifact."""
    from agents.jira import create_issue
    jira = create_issue(f)
    if jira and jira.get("status") == "jira_issue":
        return jira
    # JIRA not configured, or a transient error → keep a durable local artifact.
    d = "eval/tickets"
    os.makedirs(d, exist_ok=True)
    key = f"OPS-{abs(hash(f.get('fingerprint', f['resource']))) % 1000:03d}"
    with open(os.path.join(d, f"{key}.md"), "w") as fh:
        fh.write(f"# [{key}] {f.get('title','')}\n\n**Resource:** `{f['resource']}`  \n"
                 f"**Reason:** {reason or 'remediation via ticket (per project policy)'}  \n"
                 f"**Action:** {f.get('recommended_action','')}\n")
    return {"status": "ticket_opened", "key": key}


async def remediate(ctx, findings: list[dict[str, Any]], project: str = "") -> list[dict[str, Any]]:
    """Deliver each finding through the channels enabled by the project's action policy.

    A CHANGE-FREEZE on the project overrides the PR channel: no PR, no branch — the tool
    detects and reports only (Issue/Slack) until the freeze lifts. This is the
    change-management control in action; never touch frozen production.
    """
    from datetime import date

    from agents.freeze import FreezeStore
    from agents.policy import ActionPolicy
    actions = ActionPolicy().channels_for(project)
    frozen = FreezeStore().active(project, date.today())  # None, or {"until","reason"}

    results = []
    for f in findings:
        proof = await ctx.gateway.call_tool("remediation", "monitoring.timeseries",
                                            {"resource": f["resource"]})
        used, res = [], {"resource": f["resource"], "status": "no_channel"}
        pr_enabled = bool(actions.get("pr"))

        if pr_enabled and frozen:
            # Freeze wins over policy — record the suppression, propose nothing.
            res = {"resource": f["resource"], "status": "change_frozen",
                   "reason": (f"change-freeze until {frozen.get('until') or 'lifted manually'} "
                              f"({frozen.get('reason', '')}) — detect + report only, no PR/branch"),
                   "frozen_until": frozen.get("until")}
            ctx.observability.audit("remediation", "pr_suppressed_freeze",
                                    {"resource": f["resource"], "until": frozen.get("until")})
        elif pr_enabled:
            res = await ctx.remediation_channel.deliver({"finding": f, "proof": proof})
            used.append("pr")

        # Ticket: when PR is off/frozen, or the PR couldn't proceed (conflict/blocked).
        pr_stuck = res.get("status") in ("conflict_triage", "policy_blocked", "no_channel", "change_frozen")
        if actions.get("issue") and (not pr_enabled or frozen or pr_stuck):
            ticket = _open_ticket(f, res.get("reason", ""))
            used.append("issue")
            if res.get("status") in ("no_channel",):
                res = ticket

        if actions.get("slack"):
            ctx.observability.audit("notifier", "slack_notify",
                                    {"resource": f["resource"], "status": res.get("status")})
            used.append("slack")

        res["channels"] = used
        ctx.observability.audit("remediation", "deliver",
                                {"resource": f["resource"], "status": res.get("status"), "channels": used})
        results.append(res)
    return results
